import Vue from 'vue'
import {
    Button, Form, FormItem, Input, Row, Col, MessageBox, Radio, RadioGroup, RadioButton
    , Menu, Submenu, MenuItem, MenuItemGroup, Breadcrumb, BreadcrumbItem, Container, Header, Aside, Main, Card,
    Table, TableColumn, Switch, Pagination, Dialog, Select, Option, Checkbox, CheckboxButton, CheckboxGroup, Tree
    , Tag, Alert, Steps, Step, Tabs, TabPane, Cascader, Upload
} from 'element-ui'

Vue.use(Upload)
Vue.use(Cascader)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Alert)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Checkbox)
Vue.use(CheckboxButton)
Vue.use(CheckboxGroup)
Vue.use(Option)
Vue.use(Select)
Vue.use(Dialog)
Vue.use(Pagination)
Vue.use(Switch)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Card)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Row)
Vue.use(Col)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.component(MessageBox)
